### ISSUE TITLE
Model.definition

### ISSUE THREAD

**Issue by LeonardoGentile** [chiefy/sails-generate-controller-angular#2]
Hello,
I'm wondering how to use [Model.definition](https://github.com/chiefy/sails-generate-controller-angular/blob/9a62ecd23e1176a9515fdecc38f909fb854b8efe/templates/controller.template#L21), it seems to returns the model schema. I've searched for this function anywhere in sails and in waterline but I couln't find any docs about it. The only thing I did found was this [line](https://github.com/balderdashy/waterline/blob/63effdb480ae9bd61cd78fd534e1e513294bd98d/lib/waterline.js#L166) in the source code of waterline. Do you know more about it? (And how did you found it? :) )

I'm wondering if it is safe to use it or it is a method only meant for internal use that could expose sensitive data. Also what happens if there is relation on the schema?

Thanks in advance

**Comment by chiefy** [comment]
@LeonardoGentile I don't know much about Model.definition. Since it could potentially expose a non-public API - it probably shouldn't be used in production (as I have it rendering the JSON output). I believe I added it here as an easy way to debug  / inspect your models via an API. 

I'd head over to the Waterline repo and possibly ask your question there, sorry I have stopped using Sails since 0.10, so I am a bit out of the loop. Good luck!
